service: lambda-authorizer

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${env:NODE_ENV}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource:
            - 'arn:aws:dynamodb:eu-central-1:090302095195:table/api-rate-limiter-${env:NODE_ENV}'
  environment:
    NODE_ENV: ${env:NODE_ENV}
    ROOMLESS_JWT_SECRET: ${env:ROOMLESS_JWT_SECRET}
    AUTHORIZER_JWT_TOKEN: ${env:AUTHORIZER_JWT_SECRET}
    DEFAULT_RATE_LIMIT: 5
    ADMIN_RATE_LIMIT: 90

functions:
  authorizer:
    handler: authorizer.handler
    name: authorizer-${env:NODE_ENV}