service: lambda-authorizer

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev

functions:
  authorizer:
    handler: authorizer.handler
    name: authorizer
    events:
    - http:
          method: ANY
          path: '{proxy+}'